package com.example.goldyfly.navigation

const val ROUT_HOME= "home"
const val ROUT_ABOUT= "about"
const val ROUT_SPLASH= "splash"
const val ROUT_SIGNUP= "signup"
const val ROUT_LOGIN= "login"
const val ROUT_DETAILS= "details"
const val ROUT_PROFILE= "profile"
const val ROUT_MAIN= "main"
const val BOOKING_URL = "add"
const val VIEW_BOOKING_URL = "view"
const val ADD_CONTACT= "add_contact"
const val VIEW_CONTACT= "view_contact"
const val ADD_ACCOUNT = "add_account"
const val VIEW_ACCOUNT = "view_account"
